### ISSUE TITLE
Run "pip install -r requirements.txt"

### ISSUE THREAD

**Issue by neo-seeker** [Anil-matcha/Chat-Youtube#1]
Eager to install and run on Conda environment. But unable to find ==>   "pip install -r requirements.txt".

**Comment by AnkMister** [comment]
I am also having this issue

**Comment by Anil-matcha** [comment]
@neo-seeker @AnkMister 

Added requirements.txt file now. Please check

**Comment by neo-seeker** [comment]
Yea, that works, issue can be closed. Following the instruction " Set OPENAI_API_KEY environment variable with your openai key " . Where does the API key need to be inserted.

**Comment by itsthemoon** [comment]
you need to create a .env file then paste this in it with your actual key OPENAI_API_KEY={your key here}

**Comment by itsthemoon** [comment]
I am having the same issue as above

**Comment by Anil-matcha** [comment]
@itsthemoon What issue are you facing ?

**Comment by neo-seeker** [comment]
Hi  Anil, here is the log below. I wanted to know where the
"OPENAI_API_KEY" would be inserted. I would be great to have a video or
else some working instructions, docker or something like that. Thanks Anil.

***@***.***:/home/po/Chat-Youtube# python chat_youtube.py

Command 'python' not found, did you mean:

  command 'python3' from deb python3

  command 'python' from deb python-is-python3

***@***.***:/home/po/Chat-Youtube# python3 chat_youtube.py

Traceback (most recent call last):

  File "/home/po/Chat-Youtube/chat_youtube.py", line 4, in <module>

    index = VectorstoreIndexCreator().from_loaders([loader])

  File "pydantic/main.py", line 339, in pydantic.main.BaseModel.__init__

  File "pydantic/main.py", line 1066, in pydantic.main.validate_model

  File "pydantic/fields.py", line 439, in
pydantic.fields.ModelField.get_default

  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__

pydantic.error_wrappers.ValidationError: 1 validation error for
OpenAIEmbeddings

__root__

  Did not find openai_api_key, please add an environment variable
`OPENAI_API_KEY` which contains it, or pass  `openai_api_key` as a named
parameter. (type=value_error)

***@***.***:/home/po/Chat-Youtube#

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Anil-matcha** [comment]
@neo-seeker You need to set it as an environment variable
